# **HW02 - Разведочный анализ данных(EDA)**

### Анализ данных о симптомах сердечно-сосудистых заболеваний.
Данные: https://github.com/msamhz/GA-Lessons/blob/main/2.04-lesson-eda/datasets/Heart.csv

Age       --    Возраст\
Sex       --    Пол\
ChestPain --    Боль в груди\
RestBP    --    Давление в спокойном состоянии\
Chol      --    Уровень холестерола\
Fbs       --    Уровень сахара в крови\
RestECG   --    Кардиограмма в спокойном состоянии\
MaxHR     --    Максимальная частота сердечных сокращений\
ExAng     --    Стенокардия\
Oldpeak   --    Смещение ST сегмента на кардиограмме\
Slope     --    Наклон ST сегмента на кардиограмме\
Ca        --    Количество поражённых атеросклерозом сосудов\
Thal      --    Результаты теста на ишемию\
AHD       --    Target

### 1. Загрузка библиотек

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import plotly
import matplotlib.pyplot as plt

### 2. Загрузка и быстрый обзор данных

In [ ]:
df=pd.read_csv('Heart.csv')

In [ ]:
df.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,0
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,1
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,1
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,0
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,0

In [ ]:
df.tail()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,1
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,1
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,1
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,1
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,0

In [ ]:
df.shape

(303, 15)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  303 non-null    int64
 1   Age         303 non-null    str
 2   Sex         303 non-null    int64
 3   ChestPain   303 non-null    str
 4   RestBP      303 non-null    int64
 5   Chol        303 non-null    int64
 6   Fbs         303 non-null    int64
 7   RestECG     303 non-null    int64
 8   MaxHR       303 non-null    int64
 9   ExAng       303 non-null    int64
 10  Oldpeak     303 non-null    float64
 11  Slope       303 non-null    int64
 12  Ca          299 non-null    float64
 13  Thal        301 non-null    str
 14  AHD         303 non-null    int64
dtypes: float64(2), int64(10), str(3)
memory usage: 35.6 KB

Возраст не имеет смысла представлять строковым типом, необходимо проверить данные в этом столбце на адекватность и преобразовать в численный тип.

In [ ]:
df.Age.unique()

<StringArray>
['63', '67', '37', '41', '56', '62', '57', '53', '44', '52', '48', '54', '49',
 '64', '58', '60', '50',  '?', '66', '43', '40', '69', '59', '42', '55', '61',
 '65', '71', '51', '46', '45', '39', '68', '47', '34', '35', '29', '70', '77',
 '38', '74', '76']
Length: 42, dtype: str

In [ ]:
df["Age"]=pd.to_numeric(df["Age"], errors="coerce")

In [ ]:
df.Age.dtype

dtype('float64')

Изменён тип данных для возраста.

In [ ]:
df.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,AHD
count,303.000000,294.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000,303.000000
mean,152.000000,54.357143,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241,0.458746
std,87.612784,9.124004,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438,0.499120
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,76.500000,47.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,152.000000,55.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,1.000000

In [ ]:
df.describe(include=object)

/tmp/ipykernel_12110/3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

           ChestPain    Thal
count            303     301
unique             4       3
top     asymptomatic  normal
freq             144     166

### 3. Обработка пропусков

In [ ]:
df.isnull().sum()

Unnamed: 0    0
Age           9
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

В датасете есть колонки с пропущенными значениями: возраст(Age), ca(Ca), thallium stress test(Thal). \
ca - количество основных сосудов, поражённых атеросклерозом(из 3х). \
thallium stress test - результаты теста на ишемию.

In [ ]:
df["Age"].describe()

count    294.000000
mean      54.357143
std        9.124004
min       29.000000
25%       47.000000
50%       55.000000
75%       61.000000
max       77.000000
Name: Age, dtype: float64

Так как среднее значение и медиана совпадают, то заполним пропуски в колонке возраста средним значением.

In [ ]:
average_age=df.Age.mean()

In [ ]:
df["Age"]=df["Age"].fillna(average_age)

In [ ]:
df.Ca.describe()

count    299.000000
mean       0.672241
std        0.937438
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        3.000000
Name: Ca, dtype: float64

Проверки влияния наличия значения в столбце Ca на целевую переменную.

In [ ]:
df["Diagnosis_binary"] = (df["AHD"] > 0).astype(int)

In [ ]:
missing_by_diagnosis = df.groupby('Diagnosis_binary')['Ca'].apply(lambda x: x.isnull().sum())
missing_by_diagnosis

Diagnosis_binary
0    3
1    1
Name: Ca, dtype: int64

In [ ]:
df.groupby('Ca').AHD.mean()

Ca
0.0    0.261364
1.0    0.676923
2.0    0.815789
3.0    0.850000
Name: AHD, dtype: float64

Следовательно, отсутствие значения чаще встречается у здоровых людей. Заменим пропуски нулём, так как именно при этом значении вероятность сердечных заболеваний минимальна.

In [ ]:
df['Ca']=df['Ca'].fillna(0)

In [ ]:
df.groupby('Thal').AHD.mean()

Thal
fixed         0.666667
normal        0.222892
reversable    0.760684
Name: AHD, dtype: float64

In [ ]:
df.Thal.mode()

0    normal
Name: Thal, dtype: str

In [ ]:
missing_by_diagnosis = df.groupby('Diagnosis_binary')['Thal'].apply(lambda x: x.isnull().sum())
missing_by_diagnosis

Diagnosis_binary
0    1
1    1
Name: Thal, dtype: int64

Так как в случае колонки Thal нельзя сказать влияет ли наличие записи на постановку диагноза, исключим строки с пропуском записи в данной колонке.

In [ ]:
df=df.dropna()

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 301 entries, 0 to 302
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        301 non-null    int64
 1   Age               301 non-null    float64
 2   Sex               301 non-null    int64
 3   ChestPain         301 non-null    str
 4   RestBP            301 non-null    int64
 5   Chol              301 non-null    int64
 6   Fbs               301 non-null    int64
 7   RestECG           301 non-null    int64
 8   MaxHR             301 non-null    int64
 9   ExAng             301 non-null    int64
 10  Oldpeak           301 non-null    float64
 11  Slope             301 non-null    int64
 12  Ca                301 non-null    float64
 13  Thal              301 non-null    str
 14  AHD               301 non-null    int64
 15  Diagnosis_binary  301 non-null    int64
dtypes: float64(3), int64(11), str(2)
memory usage: 40.0 KB

### Пропуски обработаны.

### 4.Вычисление числовых характеристик данных

In [ ]:
df.Age.describe()

In [ ]:
df.Sex.describe()